version: '3.9'

services:
  model-server:
    image: tensorflow/serving
    container_name: mlzoo-model-server
    command:
    - --model_config_file=/models/models.config
    - --model_config_file_poll_wait_seconds=60
    - --allow_version_labels_for_unavailable_models=true
    ports:
    - 8501:8501
    tty: true
    volumes:
      - type: bind
        source: ./models
        target: /models/

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: mlzoo-backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - MLZOO_TF_MODEL_SERVING_URL=http://model-server:8501
  #   depends_on:
  #     - model-server
  #   volumes:
  #     - ./backend:/app
    
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: mlzoo-frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:8000