global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tensorflow-serving'
    static_configs:
      - targets: ['model-server:8501']
    metrics_path: '/monitoring/prometheus/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
